NAME        = unit_tester
CC          = cc

CFLAGS      = -Wall -Wextra -Werror -g3 -fsanitize=thread

# Chemins
SRC_DIR     = ../src
INC_DIR     = ../include
TEST_INC    = ./include

# Liste des fichiers sources à tester (SANS le main.c du projet)
# On exclut le main d'origine pour ne pas avoir deux fonctions main()
SRC_FILES   = $(SRC_DIR)/utils.c $(SRC_DIR)/init.c $(SRC_DIR)/routine.c
TEST_FILES  = main.c test_parsing.c test_mutex.c

OBJ         = $(SRC_FILES:.c=.o) $(TEST_FILES:.c=.o)

all: $(NAME)

$(NAME): $(OBJ)
	$(CC) $(CFLAGS) $(OBJ) -o $(NAME) -lpthread
	@echo "✅ Tester prêt ! Lancez ./unit_tester"

%.o: %.c
	$(CC) $(CFLAGS) -I$(INC_DIR) -I$(TEST_INC) -c $< -o $@

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re: fclean all
